version: '3.7'

services:
  redis:
    image: redis:alpine
  web:
    build: ./yt_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./yt_api/:/usr/src/yt_api/
    ports:
      - 8000:8000
    env_file:
      - ./.env.yt_api
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass

volumes:
  postgres_data: