# Generated by Django 3.1.6 on 2021-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
                ('thumbnail_default_url', models.URLField()),
                ('thumbnail_medium_url', models.URLField()),
                ('thumbnail_high_url', models.URLField()),
                ('published_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
