# Generated by Django 3.1.6 on 2021-02-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchResults',
            new_name='SearchResult',
        ),
    ]
